def anal_エラーがあります():
	try:
		print(x)
	except:
		print("There is an error!")
	finally:
		print("Error block finished")